### ISSUE TITLE
Display export table don't work

### ISSUE THREAD

**Issue by nullscode** [curlew/peinfo#1]
![图片](https://github.com/user-attachments/assets/508010af-38e2-4db2-b735-c1dc1c80cc60)
![图片](https://github.com/user-attachments/assets/57fa57d6-6b05-4562-9fb4-738a60faaede)

**Comment by curlew** [comment]
`mfc140.dll` only exports nameless symbols which currently aren't handled properly.
If you have dumpbin installed, what does `dumpbin /exports Scanner.dll` give you?

![image](https://github.com/user-attachments/assets/1db55694-c543-4a72-a203-0d4894f9474d)

**Comment by nullscode** [comment]
C:\Users\h\Documents\Workplace\PAS>dumpbin /exports Scanner.dll
Microsoft (R) COFF/PE Dumper Version 14.42.34435.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file Scanner.dll

File Type: DLL

  Section contains the following exports for Scanner.dll

    00000000 characteristics
    6525F07C time date stamp Wed Oct 11 08:46:52 2023
        0.00 version
           1 ordinal base
          70 number of functions
          70 number of names

    ordinal hint RVA      name

          1    0 00001280 ??0CxFile@@QAE@ABV0@@Z
          2    1 00001240 ??0CxFile@@QAE@XZ
          3    2 000015D0 ??0CxIOFile@@QAE@ABV0@@Z
          4    3 00001300 ??0CxIOFile@@QAE@PAU_iobuf@@@Z
          5    4 000016B0 ??0CxMemFile@@QAE@ABV0@@Z
          6    5 00001250 ??1CxFile@@UAE@XZ
          7    6 00001320 ??1CxIOFile@@UAE@XZ
          8    7 00001790 ??1CxImage@@UAE@XZ
          9    8 00001290 ??4CxFile@@QAEAAV0@ABV0@@Z
         10    9 000015F0 ??4CxIOFile@@QAEAAV0@ABV0@@Z
         11    A 000016F0 ??4CxMemFile@@QAEAAV0@ABV0@@Z
         12    B 0014822C ??_7CxFile@@6B@
         13    C 00148268 ??_7CxIOFile@@6B@
         14    D 001482E0 ??_7CxImage@@6B@
         15    E 001482A4 ??_7CxMemFile@@6B@
         16    F 00001610 ??_FCxIOFile@@QAEXXZ
         17   10 000017C0 ??_FCxImage@@QAEXXZ
         18   11 00001720 ??_FCxMemFile@@QAEXXZ
         19   12 000017D0 ??_OCxImage@@QAEXAAV0@@Z
         20   13 00001390 ?Close@CxIOFile@@UAE_NXZ
         24   14 000014E0 ?Eof@CxIOFile@@UAE_NXZ
         25   15 00001500 ?Error@CxIOFile@@UAEHXZ
         26   16 000014C0 ?Flush@CxIOFile@@UAE_NXZ
         27   17 00001550 ?GetC@CxIOFile@@UAEHXZ
         28   18 000017B0 ?GetExifInfo@CxImage@@QAEPAUtag_ExifInfo@@XZ
         29   19 00001570 ?GetS@CxIOFile@@UAEPADPADH@Z

**Comment by nullscode** [comment]
that's the Scanner.dll I use 
[Scanner.zip](https://github.com/user-attachments/files/17962714/Scanner.zip)

**Comment by nullscode** [comment]
[peinfo.zip](https://github.com/user-attachments/files/17962726/peinfo.zip)
and that's the peinfo.exe i use msvc in vs2022 to build it

**Comment by nullscode** [comment]
![图片](https://github.com/user-attachments/assets/a6e69c7d-c2d8-4c43-b528-9e3967e4f924)
i tried the new version , but still no export table, just number only.

**Comment by curlew** [comment]
Seems like 32-bit addresses cause the crash seen with `Scanner.dll` as PE32 files use different data structures.
The problem with `mfc140.dll` should be fixed by #2 though

**Comment by nullscode** [comment]
Great! Perfect!
